language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t nathzi1505/travis -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true nathzi1505/travis npm test
after_success:
    - docker build -t nathzi1505/multidockertutorial-client ./client
    - docker build -t nathzi1505/multidockertutorial-nginx ./nginx
    - docker build -t nathzi1505/multidockertutorial-server ./server
    - docker build -t nathzi1505/multidockertutorial-worker ./worker
    
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Retrieve those images and push to DockerHub
    - docker push nathzi1505/multidockertutorial-client
    - docker push nathzi1505/multidockertutorial-nginx
    - docker push nathzi1505/multidockertutorial-server
    - docker push nathzi1505/multidockertutorial-worker
